"""
AWS IAM actions -> capabilities: an explicit table, as CLAUDE.md asks a real
connector to carry, instead of leaning on verb heuristics.

The base is AWS's own classification. `data/action_levels.json` is generated by
`tools/build_aws_action_levels.py` from the machine-readable Service Reference
(455 services, ~22,000 actions at generation time) and maps every action to its
IAM access level:

    List, Read  -> READ
    Write       -> WRITE   (Delete*/Terminate*/... -> DESTROY, see below)
    Permissions management -> MANAGE_PERMISSION   (AWS hands this one over free)
    Tagging     -> WRITE

Access level answers "what kind of API call is this", not "how much harm does
holding it confer", so a short list of overrides follows, each because the
level understates the harm. AWS files all of these under plain Write:

* **IMPERSONATE** -- `sts:AssumeRole*`, `iam:PassRole`, federation: holding it
  makes you someone else.
* **MANAGE_IDENTITY** -- minting or resetting credentials for other principals.
* **MANAGE_SECURITY_CONTROL** -- stopping the audit trail and the detectors
  that would notice everything else.
* **DEPLOY** -- shipping code or infrastructure.
* **DESTROY** -- Write actions whose verb deletes or terminates.
* **READ** for `kms:Decrypt` and friends, which AWS classes as Write but which
  *read* protected data (and are privileged on a key store, like any secret).

Policy action patterns (`s3:Get*`, `iam:*`, `*`) are expanded against the table.
A whole-service or global wildcard is ADMIN: it is every action, including the
ones that change who can do what. An action AWS does not list falls back to
`Capability.from_token`, and if that cannot place it, UNKNOWN -- retained and
counted against coverage, never defaulted to READ.
"""

import fnmatch
import json
from functools import lru_cache
from pathlib import Path

from app.models.capability import Capability

_DATA = Path(__file__).resolve().parent / "data" / "action_levels.json"

LEVEL_CAPABILITY = {
    "L": Capability.READ,
    "R": Capability.READ,
    "W": Capability.WRITE,
    "P": Capability.MANAGE_PERMISSION,
    "T": Capability.WRITE,
}

OVERRIDES: dict[str, Capability] = {
    # Becoming someone else.
    "sts:assumerole": Capability.IMPERSONATE,
    "sts:assumerolewithsaml": Capability.IMPERSONATE,
    "sts:assumerolewithwebidentity": Capability.IMPERSONATE,
    "sts:assumeroot": Capability.IMPERSONATE,
    "sts:getfederationtoken": Capability.IMPERSONATE,
    "iam:passrole": Capability.IMPERSONATE,
    # Minting or resetting other principals' credentials.
    "iam:createuser": Capability.MANAGE_IDENTITY,
    "iam:createaccesskey": Capability.MANAGE_IDENTITY,
    "iam:updateaccesskey": Capability.MANAGE_IDENTITY,
    "iam:createloginprofile": Capability.MANAGE_IDENTITY,
    "iam:updateloginprofile": Capability.MANAGE_IDENTITY,
    "iam:createservicespecificcredential": Capability.MANAGE_IDENTITY,
    "iam:resetservicespecificcredential": Capability.MANAGE_IDENTITY,
    "iam:deactivatemfadevice": Capability.MANAGE_IDENTITY,
    "iam:uploadsshpublickey": Capability.MANAGE_IDENTITY,
    "cognito-idp:admincreateuser": Capability.MANAGE_IDENTITY,
    "cognito-idp:adminsetuserpassword": Capability.MANAGE_IDENTITY,
    "identitystore:createuser": Capability.MANAGE_IDENTITY,
    # Blinding the controls that would notice.
    "cloudtrail:stoplogging": Capability.MANAGE_SECURITY_CONTROL,
    "cloudtrail:deletetrail": Capability.MANAGE_SECURITY_CONTROL,
    "cloudtrail:updatetrail": Capability.MANAGE_SECURITY_CONTROL,
    "cloudtrail:puteventselectors": Capability.MANAGE_SECURITY_CONTROL,
    "guardduty:deletedetector": Capability.MANAGE_SECURITY_CONTROL,
    "guardduty:updatedetector": Capability.MANAGE_SECURITY_CONTROL,
    "guardduty:disassociatefromadministratoraccount": Capability.MANAGE_SECURITY_CONTROL,
    "config:stopconfigurationrecorder": Capability.MANAGE_SECURITY_CONTROL,
    "config:deleteconfigurationrecorder": Capability.MANAGE_SECURITY_CONTROL,
    "config:deletedeliverychannel": Capability.MANAGE_SECURITY_CONTROL,
    "securityhub:disablesecurityhub": Capability.MANAGE_SECURITY_CONTROL,
    "securityhub:batchdisablestandards": Capability.MANAGE_SECURITY_CONTROL,
    "access-analyzer:deleteanalyzer": Capability.MANAGE_SECURITY_CONTROL,
    "macie2:disablemacie": Capability.MANAGE_SECURITY_CONTROL,
    "inspector2:disable": Capability.MANAGE_SECURITY_CONTROL,
    "detective:deletegraph": Capability.MANAGE_SECURITY_CONTROL,
    "logs:deleteloggroup": Capability.MANAGE_SECURITY_CONTROL,
    "logs:deletelogstream": Capability.MANAGE_SECURITY_CONTROL,
    "logs:putretentionpolicy": Capability.MANAGE_SECURITY_CONTROL,
    "cloudwatch:deletealarms": Capability.MANAGE_SECURITY_CONTROL,
    "cloudwatch:disablealarmactions": Capability.MANAGE_SECURITY_CONTROL,
    "backup:deletebackupvault": Capability.MANAGE_SECURITY_CONTROL,
    "backup:deleterecoverypoint": Capability.MANAGE_SECURITY_CONTROL,
    # Shipping code or infrastructure.
    "lambda:createfunction": Capability.DEPLOY,
    "lambda:updatefunctioncode": Capability.DEPLOY,
    "lambda:updatefunctionconfiguration": Capability.DEPLOY,
    "lambda:publishversion": Capability.DEPLOY,
    "cloudformation:createstack": Capability.DEPLOY,
    "cloudformation:updatestack": Capability.DEPLOY,
    "cloudformation:executechangeset": Capability.DEPLOY,
    "ecs:updateservice": Capability.DEPLOY,
    "ecs:createservice": Capability.DEPLOY,
    "ecs:registertaskdefinition": Capability.DEPLOY,
    "codedeploy:createdeployment": Capability.DEPLOY,
    "elasticbeanstalk:updateenvironment": Capability.DEPLOY,
    "ecr:putimage": Capability.DEPLOY,
    "apprunner:startdeployment": Capability.DEPLOY,
    "amplify:startdeployment": Capability.DEPLOY,
    # Reads AWS files under Write.
    "kms:decrypt": Capability.READ,
    "kms:generatedatakey": Capability.READ,
    "kms:reencryptfrom": Capability.READ,
    "kms:schedulekeydeletion": Capability.DESTROY,
}

_DESTROY_VERBS = ("delete", "terminate", "destroy", "purge", "remove", "disable")


@lru_cache(maxsize=1)
def _services() -> dict:
    return json.loads(_DATA.read_text(encoding="utf-8"))["services"]


@lru_cache(maxsize=1)
def action_levels() -> dict[str, dict[str, str]]:
    """{service: {action_lowercase: access level}}."""
    return {svc: {a: v[0] for a, v in data["actions"].items()} for svc, data in _services().items()}


def action_resource_types(service: str) -> dict[str, list[str]]:
    """{action_lowercase: [resource type names it can target]} -- empty means account-level."""
    return {a: v[1] for a, v in _services().get(service, {}).get("actions", {}).items()}


@lru_cache(maxsize=None)
def arn_patterns(service: str) -> dict[str, tuple[str, ...]]:
    """{resource type: ARN glob patterns}, AWS's `${Var}` placeholders made `*`."""
    import re

    resources = _services().get(service, {}).get("resources", {})
    return {
        rtype: tuple(re.sub(r"\$\{[^}]*\}", "*", f) for f in formats)
        for rtype, formats in resources.items()
    }


def capability_of_action(action: str) -> Capability:
    """One concrete action, e.g. "s3:DeleteObject". Never raises."""
    key = action.strip().lower()
    if key in OVERRIDES:
        return OVERRIDES[key]
    service, _, name = key.partition(":")
    level = action_levels().get(service, {}).get(name)
    if level is None:
        return Capability.from_token(key)
    if level == "W" and name.startswith(_DESTROY_VERBS):
        return Capability.DESTROY
    return LEVEL_CAPABILITY[level]


def capabilities_of_pattern(pattern: str) -> frozenset[Capability]:
    """
    What a policy's action pattern confers: "*" and "svc:*" are ADMIN; any other
    wildcard is the union over the AWS actions it matches (falling back to the
    verb heuristics, then UNKNOWN, when it matches none).
    """
    key = pattern.strip().lower()
    if key == "*" or (key.endswith(":*") and key.count(":") == 1):
        return frozenset({Capability.ADMIN})
    if "*" not in key and "?" not in key:
        return frozenset({capability_of_action(key)})
    service, _, name_pattern = key.partition(":")
    names = action_levels().get(service, {})
    matched = [n for n in names if fnmatch.fnmatchcase(n, name_pattern)]
    if not matched:
        return frozenset({Capability.from_token(key.replace("*", "").replace("?", ""))})
    return frozenset(capability_of_action(f"{service}:{n}") for n in matched)


def actions_matching(patterns, service: str) -> list[str]:
    """Concrete actions of one service matched by any of the patterns (for NotAction)."""
    names = action_levels().get(service, {})
    out = []
    for name in names:
        full = f"{service}:{name}"
        if any(fnmatch.fnmatchcase(full, p.strip().lower()) for p in patterns):
            out.append(full)
    return out
